-- MySQL Script generated by MySQL Workbench
-- Mo 08 Nov 2021 13:10:51
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='ONLY_FULL_GROUP_BY,STRICT_TRANS_TABLES,NO_ZERO_IN_DATE,NO_ZERO_DATE,ERROR_FOR_DIVISION_BY_ZERO,NO_ENGINE_SUBSTITUTION';

-- -----------------------------------------------------
-- Schema dfem
-- -----------------------------------------------------

-- -----------------------------------------------------
-- Schema dfem
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `dfem` ;
USE `dfem` ;

-- -----------------------------------------------------
-- Table `dfem`.`dfem_authentications`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `dfem`.`dfem_authentications` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `email_hashed` VARCHAR(100) NULL,
  `language` VARCHAR(10) NULL,
  `onetimepassword` VARCHAR(45) NULL,
  `passwordcreated` INT NULL,
  `timecreated` INT NULL,
  `timelastlogin` INT NULL,
  PRIMARY KEY (`id`),
  UNIQUE INDEX `email_hashed_UNIQUE` (`email_hashed` ASC) VISIBLE)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `dfem`.`dfem_personas`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `dfem`.`dfem_personas` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `authid` INT NULL,
  `age` INT NULL,
  `gender` VARCHAR(1) NULL,
  `industry` VARCHAR(45) NULL,
  `academiclevel` VARCHAR(45) NULL,
  `residual` VARCHAR(45) NULL,
  `nationality` VARCHAR(45) NULL,
  `timecreated` VARCHAR(45) NULL,
  `timemodified` INT NULL,
  PRIMARY KEY (`id`),
  INDEX `userid` (`authid` ASC) VISIBLE,
  CONSTRAINT `fk_persondata_1`
    FOREIGN KEY (`authid`)
    REFERENCES `dfem`.`dfem_authentications` (`id`)
    ON DELETE SET NULL
    ON UPDATE SET NULL)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `dfem`.`dfem_toolcategories`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `dfem`.`dfem_toolcategories` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `category` VARCHAR(45) NULL,
  PRIMARY KEY (`id`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `dfem`.`dfem_tools`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `dfem`.`dfem_tools` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `name` VARCHAR(45) NULL,
  `archetype` VARCHAR(45) NULL,
  `toolcategory` INT NULL,
  PRIMARY KEY (`id`),
  INDEX `fk_dfem_tools_1_idx` (`toolcategory` ASC) VISIBLE,
  CONSTRAINT `fk_dfem_tools_1`
    FOREIGN KEY (`toolcategory`)
    REFERENCES `dfem`.`dfem_toolcategories` (`id`)
    ON DELETE CASCADE
    ON UPDATE CASCADE)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `dfem`.`dfem_estimations`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `dfem`.`dfem_estimations` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `authid` INT NULL,
  `toolid` INT NULL,
  `timecreated` INT NULL,
  `timemodified` INT NULL,
  PRIMARY KEY (`id`),
  INDEX `fk_dfem_estimations_2_idx` (`toolid` ASC) VISIBLE,
  INDEX `fk_dfem_estimations_1_idx` (`authid` ASC) VISIBLE,
  CONSTRAINT `fk_dfem_estimations_1`
    FOREIGN KEY (`authid`)
    REFERENCES `dfem`.`dfem_personas` (`id`)
    ON DELETE CASCADE
    ON UPDATE CASCADE,
  CONSTRAINT `fk_dfem_estimations_2`
    FOREIGN KEY (`toolid`)
    REFERENCES `dfem`.`dfem_tools` (`id`)
    ON DELETE CASCADE
    ON UPDATE CASCADE)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `dfem`.`dfem_ratings`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `dfem`.`dfem_ratings` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `estimationid` INT NULL,
  `origin1` TINYINT(1) NULL,
  `origin2` TINYINT(1) NULL,
  `origin3` TINYINT(1) NULL,
  `origin4` TINYINT(1) NULL,
  `granularity1` TINYINT(1) NULL,
  `granularity2` TINYINT(1) NULL,
  `granularity3` TINYINT(1) NULL,
  `transparency1` TINYINT(1) NULL,
  `transparency2` TINYINT(1) NULL,
  `transparency3` TINYINT(1) NULL,
  `transparency4` TINYINT(1) NULL,
  `transparency5` TINYINT(1) NULL,
  `transparency6` TINYINT(1) NULL,
  `goals1` TINYINT(1) NULL,
  `goals2` TINYINT(1) NULL,
  `goals3` TINYINT(1) NULL,
  `goals4` TINYINT(1) NULL,
  `goals5` TINYINT(1) NULL,
  `location1` TINYINT(1) NULL,
  `location2` TINYINT(1) NULL,
  `location3` TINYINT(1) NULL,
  `location4` TINYINT(1) NULL,
  `location5` TINYINT(1) NULL,
  `means1` TINYINT(1) NULL,
  `means2` TINYINT(1) NULL,
  `means3` TINYINT(1) NULL,
  `means4` TINYINT(1) NULL,
  `means5` TINYINT(1) NULL,
  `benefits1` TINYINT(1) NULL,
  `benefits2` TINYINT(1) NULL,
  `benefits3` TINYINT(1) NULL,
  `benefits4` TINYINT(1) NULL,
  PRIMARY KEY (`id`),
  INDEX `fk_dfem_ratings_1_idx` (`estimationid` ASC) VISIBLE,
  CONSTRAINT `fk_dfem_ratings_1`
    FOREIGN KEY (`estimationid`)
    REFERENCES `dfem`.`dfem_estimations` (`id`)
    ON DELETE CASCADE
    ON UPDATE CASCADE)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `dfem`.`dfem_results`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `dfem`.`dfem_results` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `estimationid` INT NULL,
  `control` INT NULL,
  `intention` INT NULL,
  `protection` INT NULL,
  `objective` INT NULL,
  `fortune` INT NULL,
  PRIMARY KEY (`id`),
  INDEX `fk_dfem_results_1_idx` (`estimationid` ASC) VISIBLE,
  CONSTRAINT `fk_dfem_results_1`
    FOREIGN KEY (`estimationid`)
    REFERENCES `dfem`.`dfem_estimations` (`id`)
    ON DELETE CASCADE
    ON UPDATE CASCADE)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `dfem`.`dfem_sharings`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `dfem`.`dfem_sharings` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `estimationid` INT NOT NULL,
  `s` VARCHAR(45) NOT NULL,
  `timecreated` INT NULL,
  `timeexpired` INT NULL,
  PRIMARY KEY (`id`),
  INDEX `fk_dfem_shared_1_idx` (`estimationid` ASC) VISIBLE,
  CONSTRAINT `fk_dfem_shared_1`
    FOREIGN KEY (`estimationid`)
    REFERENCES `dfem`.`dfem_estimations` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
