-- MySQL Script generated by MySQL Workbench
-- Do 04 Nov 2021 18:17:41
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='ONLY_FULL_GROUP_BY,STRICT_TRANS_TABLES,NO_ZERO_IN_DATE,NO_ZERO_DATE,ERROR_FOR_DIVISION_BY_ZERO,NO_ENGINE_SUBSTITUTION';

-- -----------------------------------------------------
-- Schema dfem
-- -----------------------------------------------------

-- -----------------------------------------------------
-- Schema dfem
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `dfem` ;
USE `dfem` ;

-- -----------------------------------------------------
-- Table `dfem`.`dfem_authentications`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `dfem`.`dfem_authentications` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `email_hashed` VARCHAR(100) NULL,
  PRIMARY KEY (`id`),
  UNIQUE INDEX `email_hashed_UNIQUE` (`email_hashed` ASC) VISIBLE)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `dfem`.`dfem_estimations`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `dfem`.`dfem_estimations` (
  `id` INT NOT NULL,
  `userid` INT NULL,
  `toolid` INT NULL,
  `timecreated` INT NULL,
  PRIMARY KEY (`id`),
  INDEX `fk_dfem_estimations_1_idx` (`userid` ASC) VISIBLE,
  INDEX `fk_dfem_estimations_2_idx` (`toolid` ASC) VISIBLE,
  CONSTRAINT `fk_dfem_estimations_1`
    FOREIGN KEY (`userid`)
    REFERENCES `dfem`.`dfem_authentications` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_dfem_estimations_2`
    FOREIGN KEY (`toolid`)
    REFERENCES `dfem`.`dfem_tools` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `dfem`.`dfem_personas`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `dfem`.`dfem_personas` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `userid` INT NULL,
  `attributename` VARCHAR(45) NULL,
  `attributevalue` VARCHAR(255) NULL,
  PRIMARY KEY (`id`),
  INDEX `userid` (`userid` ASC) VISIBLE,
  CONSTRAINT `fk_persondata_1`
    FOREIGN KEY (`userid`)
    REFERENCES `dfem`.`dfem_authentications` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `dfem`.`dfem_ratings`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `dfem`.`dfem_ratings` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `estimationid` INT NULL,
  `origin1` TINYINT(1) NULL,
  `origin2` TINYINT(1) NULL,
  `origin3` TINYINT(1) NULL,
  `origin4` TINYINT(1) NULL,
  `granularity1` TINYINT(1) NULL,
  `granularity2` TINYINT(1) NULL,
  `granularity3` TINYINT(1) NULL,
  `transparency1` TINYINT(1) NULL,
  `transparency2` TINYINT(1) NULL,
  `transparency3` TINYINT(1) NULL,
  `transparency4` TINYINT(1) NULL,
  `transparency5` TINYINT(1) NULL,
  `transparency6` TINYINT(1) NULL,
  `goals1` TINYINT(1) NULL,
  `goals2` TINYINT(1) NULL,
  `goals3` TINYINT(1) NULL,
  `goals4` TINYINT(1) NULL,
  `goals5` TINYINT(1) NULL,
  `location1` TINYINT(1) NULL,
  `location2` TINYINT(1) NULL,
  `location3` TINYINT(1) NULL,
  `location4` TINYINT(1) NULL,
  `location5` TINYINT(1) NULL,
  `means1` TINYINT(1) NULL,
  `means2` TINYINT(1) NULL,
  `means3` TINYINT(1) NULL,
  `means4` TINYINT(1) NULL,
  `means5` TINYINT(1) NULL,
  `benefits1` TINYINT(1) NULL,
  `benefits2` TINYINT(1) NULL,
  `benefits3` TINYINT(1) NULL,
  `benefits4` TINYINT(1) NULL,
  PRIMARY KEY (`id`),
  INDEX `fk_dfem_ratings_1_idx` (`estimationid` ASC) VISIBLE,
  CONSTRAINT `fk_dfem_ratings_1`
    FOREIGN KEY (`estimationid`)
    REFERENCES `dfem`.`dfem_estimations` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `dfem`.`dfem_tools`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `dfem`.`dfem_tools` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `name` VARCHAR(45) NULL,
  `archetype` VARCHAR(45) NULL,
  PRIMARY KEY (`id`))
ENGINE = InnoDB;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
